#include <iostream>
#include <stack>
#include <memory>
#include <map>
#include <list>
#include <assert.h>
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>
#include <SFML/Audio.hpp>
